version: '3.8'
services:
  test-back:
    build:
      context: .
      dockerfile: ./testutils/docker/Dockerfile.backend
    volumes:
      - .:/app
    depends_on:
      test-db:
        condition: service_healthy
    container_name: mc-test-back
    command: go test -cover ./...

  test-db:
    build:
      context: .
      dockerfile: ./testutils/docker/Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    container_name: mc-test-db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -proot
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s