name: バックエンド単体テスト

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # 手動での実行を許可
  workflow_dispatch:

jobs:

  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        docker-compose -f ./back-end/docker-compose.test.yml up -d
        docker-compose -f ./back-end/docker-compose.test.yml exec -T test-back sh -c "go test -cover ./..."
