name: フロントエンド単体テスト

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'
      - '.github/workflows/unit-test-front.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'front-end/**'
      - '.github/workflows/unit-test-front.yml'

  # 手動での実行を許可
  workflow_dispatch:

jobs:

  unit_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        docker build -t unittest ./front-end/
        docker run unittest npm run test:unit
